version: '3.8'

services:
  frontend:
    image: 074004850075.dkr.ecr.us-east-1.amazonaws.com/codecase:frontend
    container_name: frontend
    ports:
      - "5173:80"  # Expose only for internal test (Nginx will proxy later)

  backend:
    image: 074004850075.dkr.ecr.us-east-1.amazonaws.com/codecase:backend
    container_name: backend
    ports:
      - "5000:5000"

  compiler:
    image: 074004850075.dkr.ecr.us-east-1.amazonaws.com/codecase:compiler
    container_name: compiler
    ports:
      - "7000:7000"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - compiler
