version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "5160:80"
    depends_on:
      - backend
      - compiler
    restart: unless-stopped
  backend:
    build: ./backend
    ports:
      - "5600:5600"
    environment:
      - .env
    restart: unless-stopped
  compiler:
    build: ./compilerNode
    ports:
      - "7600:7600"
    environment:
      - .env
    restart: unless-stopped