version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "5170:80"
    depends_on:
      - backend
      - compiler
    restart: unless-stopped
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - .env
    restart: unless-stopped
  compiler:
    build: ./compilerNode
    ports:
      - "7000:7000"
    environment:
      - .env
    restart: unless-stopped